### ISSUE TITLE
setupenv.py creates a profile file wherever setup is run

### ISSUE THREAD

**Issue by IanWhalen** [mongodb/server-workflow-tool#10]
https://github.com/mongodb/server-workflow-tool/blob/a6b505385e73768d631b094ea87bb6fc476b1c2c/mongodb_cmdline_tool/setupenv.py#L131

As per above, running `m` puts a Profile file wherever it is run, which presumably not what we want to happen since it once again can pollute the mongo tree.  Need to know where to put this and I can make the change to put it there.

**Comment by IanWhalen** [comment]
@guoyr need you to confirm this is what's happening and that it's incorrec.t  if you tell me where to put the file I can open a PR.

**Comment by guoyr** [comment]
Yeah that looks about right. I think `profile` should be changed to `~/.bashrc` and the open mode should be changed from `w` to `w+`. If the user wants to use a different shell, they should already know how to port over configurations and can do it themselves.

**Comment by visemet** [comment]
> Yeah that looks about right. I think `profile` should be changed to `~/.bashrc` and the open mode should be changed from `w` to `w+`.

Do you mean `a` (append)? I don't see why setupenv.py should truncate a user's bashrc file.

**Comment by guoyr** [comment]
☝️yeah. I'm going to get some coffee.
