### ISSUE TITLE
clang-format gets installed wherever you run `m`

### ISSUE THREAD

**Issue by IanWhalen** [mongodb/server-workflow-tool#9]
We can close if I've misunderstood something here, but in running `m lint` for  the first time, clang-format gets downloaded placed in the same directory you've run m in.  In my case that was the root of `./mongo/`.

Presumably that's not a good or common place because it is not in the .gitignore file but it is still in the repo path.  Would appreciate some guidance on where it should go and then I can update this script to be more explicit.

**Comment by IanWhalen** [comment]
or maybe it's just using that as a temporary location?

**Comment by IanWhalen** [comment]
@guoyr does it seem accurate that this is happening?  and something we should fix?

**Comment by guoyr** [comment]
Thanks for catching this Ian; your description seems accurate. I think `~/bin` is a more preferable location, where it'll go alongside the `evergreen` binary

**Comment by guoyr** [comment]
We have to manually move `clang-format` into `~/bin` because it always gets installed into `mongo`: https://github.com/mongodb/mongo/blob/724615ae608b123bb2e82dc0731f8e61fab17a82/buildscripts/clang_format.py#L296
